# Generated by Django 5.0.1 on 2024-01-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('numero_piece', models.IntegerField()),
                ('type_piece', models.CharField(max_length=25)),
                ('date_livrance', models.DateTimeField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateTimeField()),
                ('code_postal', models.CharField(max_length=10)),
                ('sexe', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
