# Generated by Django 5.0.1 on 2024-01-26 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafika', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='address',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='adresse',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='code_postal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_livrance',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='matricule',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='numero_piece',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='type_piece',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='BeneficiaireModifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modifie', models.CharField(default='', max_length=255)),
                ('prenom_modif', models.CharField(default='', max_length=255)),
                ('matricule_modif', models.CharField(default='', max_length=255)),
                ('numero_piece_modif', models.CharField(default='', max_length=25)),
                ('type_piece_modif', models.CharField(default='', max_length=25)),
                ('date_livrance_modif', models.DateTimeField(default='')),
                ('telephone_modif', models.CharField(default='', max_length=25)),
                ('email_modif', models.EmailField(default='', max_length=254)),
                ('date_naissance_modif', models.CharField(default='', max_length=25)),
                ('code_postal_modif', models.CharField(default='', max_length=10)),
                ('sexe_modif', models.CharField(default='', max_length=10)),
                ('adresse_modif', models.CharField(default='', max_length=25)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafika.beneficiaire')),
            ],
        ),
    ]
