# Generated by Django 5.0.1 on 2024-01-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafika', '0002_remove_beneficiaire_address_beneficiaire_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='adresse_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='code_postal_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='date_livrance_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='date_naissance_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='email_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='matricule_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='nom_modifie',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='numero_piece_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='prenom_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='sexe_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='telephone_modif',
        ),
        migrations.RemoveField(
            model_name='beneficiairemodifie',
            name='type_piece_modif',
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_livrance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='matricule',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='numero_piece',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='type_piece',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiairemodifie',
            name='beneficiaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tafika.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='beneficiairemodifie',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
