# Generated by Django 5.0.1 on 2024-01-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tafika', '0002_alter_beneficiaire_date_naissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='address',
            new_name='adresse',
        ),
    ]
