# Generated by Django 5.0.1 on 2024-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafika', '0003_rename_address_beneficiaire_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='numero_piece',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(max_length=25),
        ),
    ]
