# Generated by Django 5.0.1 on 2024-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafika', '0003_remove_beneficiairemodifie_adresse_modif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
    ]
